import localFont from 'next/font/local';
import '@/assets/styles/globals.css';
import Navbar from '@/components/navbar';
import QueryProvider from './providers/QueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Toaster } from '@/components/ui/toaster';
import { auth } from '@/auth';
import { SignInButton } from '@/components/sign-in-button';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'LitaLife App',
  description: 'Generated by Ahmad Azizyar',
};

export default async function RootLayout({ children }) {
  const session = await auth();
  if (session?.user.name == 'ilxli-nl') {
    return (
      <html lang='en'>
        <QueryProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Navbar />
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
            <Toaster />
          </body>
        </QueryProvider>
      </html>
    );
  }

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='bg-slate-300 grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 sm:p-20 font-[family-name:var(--font-geist-sans)]'>
          <main className='flex flex-col gap-8 row-start-2 items-center sm:items-start'>
            <p> You Are Not Signed In</p> <SignInButton />
          </main>
        </div>
      </body>
    </html>
  );
}
